# Generated by Django 3.0.5 on 2020-06-05 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0002_auto_20200503_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhappinessdata',
            name='exercise',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='userhappinessdata',
            name='happy',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Happiness'),
        ),
        migrations.AlterField(
            model_name='userhappinessdata',
            name='metime',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Alone Time'),
        ),
        migrations.AlterField(
            model_name='userhappinessdata',
            name='sleep',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Sleep'),
        ),
        migrations.AlterField(
            model_name='userhappinessdata',
            name='social',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Social'),
        ),
        migrations.AlterField(
            model_name='userhappinessdata',
            name='socialmedia',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Social Media'),
        ),
        migrations.AlterField(
            model_name='userhappinessdata',
            name='weather',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Weather'),
        ),
    ]
