# Generated by Django 3.0.5 on 2020-06-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0003_auto_20200605_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhappinessdata',
            name='journal',
            field=models.TextField(default='No entry', verbose_name='Journal'),
            preserve_default=False,
        ),
    ]
